updated with tested job

diff --git a/rundeck-jobs/bosh-restart-job.yml b/rundeck-jobs/bosh-restart-job.yml
--- a/rundeck-jobs/bosh-restart-job.yml
+++ b/rundeck-jobs/bosh-restart-job.yml
@@ -1,93 +1,119 @@
 - description: Restarts a bosh job (service VM)
   executionEnabled: true
+  id: 6c5bb057-3dc4-4d6e-937b-eb4520215f20
   loglevel: INFO
-  name: bosh-restart-job-dev
+  name: bosh-restart-job
   nodefilters:
     dispatch:
       excludePrecedence: true
       keepgoing: false
       rankOrder: ascending
       threadcount: 1
-  nodesSelectedByDefault: true
+    filter: 'tags: pcf-dev,pcf-prod-dc20'
+  nodesSelectedByDefault: false
   options:
-  - description: The IP of the Bosh director
-    name: bosh-director-ip
-    value: 10.35.39.3
-  - description: The bosh user's password.
-    name: bosh-password
-    secure: true
-    value: f893b1e36b697631a98a
-    valueExposed: true
-  - description: The user to log into the Bosh director as.
-    name: bosh-user
-    value: director
+  - description: Set this value to '1' to update the scripts from source control.
+    name: clean
+    value: '0'
+    values:
+    - '0'
+    - '1'
   - description: The name pre-fix of the deployment
     name: deployment
+    required: true
   - description: The name pre-fix of the job to restart
     name: job
+  - description: The ops manager user's password.
+    name: opsman-password
+    required: true
+    secure: true
+    value: 2Secret4CF
+    valueExposed: true
   scheduleEnabled: true
   sequence:
     commands:
     - script: |
         #!/bin/bash
 
-        set -e
         #set -x
 
-        director_ip="@option.bosh-director-ip@"
-        user="@option.bosh-user@"
-        password="@option.bosh-password@"
+        #
+        # Setup workspace
+        #
+
+        [ -z "@node.bitbucket@" ] && (
+          echo "ERROR! The Rundeck node environment variable \"bitbucket\" has not been set."
+          exit 1
+        )
+        [ -z "@node.opsman-host@" ] && (
+          echo "ERROR! The Rundeck node environment variable \"opsman-host\" has not been set."
+          exit 1
+        )
+        [ -z "@node.opsman-user@" ] && (
+          echo "ERROR! The Rundeck node environment variable \"opsman-user\" has not been set."
+          exit 1
+        )
+        [ -z "@option.opsman-password@" ] && (
+          echo "ERROR! The Ops Manager administration UI password needs to be provided."
+          exit 1
+        )
+        [ -z "@node.pcf-config@" ] && (
+          echo "ERROR! The Rundeck node environment variable \"pcf-config\" has not been set."
+          exit 1
+        )
+
+        export ROOT_DIR=$HOME/workspace/scripts
+        export DOWNLOADS_DIR=$HOME/workspace/downloads
+        export BACKUP_DIR=$HOME/workspace/backups
+        export CONFIG_DIR=$HOME/workspace/configs
+
+        if [ "@option.clean@" == "1" ]; then
+            rm -fr $DOWNLOADS_DIR
+            rm -fr $ROOT_DIR
+            rm -fr $CONFIG_DIR
+        fi
+        mkdir -p $DOWNLOADS_DIR
+        mkdir -p $BACKUP_DIR
+        mkdir -p $CONFIG_DIR
+
+        if [[ ! -e $ROOT_DIR ]]; then
+            git_host="@node.bitbucket@"
+            git clone ssh://git@$git_host:7999/cloudf/pcf-automation.git --branch master --single-branch $ROOT_DIR
+            pushd $ROOT_DIR
+            git checkout master
+            popd
+        else
+            pushd $ROOT_DIR
+            git checkout master
+            git pull
+            popd
+        fi
+        	
+        #
+        # Initialize script
+        #
+
+        opsman_host="@node.opsman-host@"
+        opsman_user="@node.opsman-user@"
+        opsman_password="@option.opsman-password@"
+
         dep_prefix="@option.deployment@"
         job_prefix="@option.job@"
 
-        export BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/bosh/Gemfile 
-        bosh="bundle exec bosh"
+        source $ROOT_DIR/scripts/opsman-func.sh
+        source $ROOT_DIR/scripts/bosh-func.sh
 
         #
-        # Target director and login if not logged in
+        # Login to Bosh and restart job
         #
 
-        bosh_status=$($bosh status)
-        echo -e "Bosh status..."
-        echo -e "$bosh_status"
-
-        logged_in_user=$(echo -e "$bosh_status" | awk '/User/{ print $ 2}')
-        if [[ "$user" != "$logged_in_user" ]]; then
-            $bosh logout
-            echo -e "Targetting director."
-            echo -e "$user\n$password" | $bosh --ca-cert //var/tempest/workspaces/default/root_ca_certificate target $director_ip
-        fi
-
-        deployment=$($bosh deployments | awk -v d="$dep_prefix-" '$2~d { print $2 }')
-        if [[ -z $deployment ]]; then
-            echo "Unable to determine name for deployment prefix '$dep_prefix'."
-            exit 1
-        fi
-
-        rm -f $dep_prefix.yml
-        $bosh download manifest $deployment $dep_prefix.yml
-        $bosh deployment $dep_prefix.yml
-
-        bosh_vms=$($bosh vms $deployment --vitals)
-        echo -e "Status of all VMs in deployment '$deployment'..."
-        echo -e "$bosh_vms"
-
-        if [[ -n $job_prefix ]]; then
-            for j in $(echo -e "$bosh_vms" | awk -v j="$job_prefix-" '$2~j { print $2 }'); do
-                job_name=${j%%/*}
-                job_index=${j##*/}
-                echo "Stopping job '$job_name' index '$job_index'..."
-                echo "yes" | $bosh stop $job_name $job_index
-            done
-            for j in $(echo -e "$bosh_vms" | awk -v j="$job_prefix-" '$2~j { print $2 }'); do
-                job_name=${j%%/*}
-                job_index=${j##*/}
-                echo "Starting job '$job_name' index '$job_index'..."
-                echo "yes" | $bosh start $job_name $job_index
-            done
-        fi
+        opsman::login $opsman_host $opsman_user $opsman_password 
+        bosh::login $(opsman::get_director_ip) $(opsman::get_director_user) $(opsman::get_director_password)
+        bosh::set_deployment $dep_prefix
+        bosh::vms $bosh_deployment
+        bosh::restart_job $job_prefix
 
         #set +x
-        set +e
     keepgoing: false
     strategy: node-first
+  uuid: 6c5bb057-3dc4-4d6e-937b-eb4520215f20
