added checks for additional rundeck variables

diff --git a/rundeck-jobs/pcf-backup.yml b/rundeck-jobs/pcf-backup.yml
--- a/rundeck-jobs/pcf-backup.yml
+++ b/rundeck-jobs/pcf-backup.yml
@@ -49,8 +49,16 @@
         	echo "ERROR! The Rundeck node environment variable \"opsman-user\" has not been set."
         	exit 1
         )
+        [ -z "@option.opsman-password@" ] && (
+        	echo "ERROR! The Rundeck job runtime variable \"opsman-password\" has not been set."
+        	exit 1
+        )
         [ -z "@node.opsman-ssh-user@" ] && (
-        	echo "ERROR! The Rundeck node environment variable \".opsman-ssh-user\" has not been set."
+        	echo "ERROR! The Rundeck node environment variable \"opsman-ssh-user\" has not been set."
+        	exit 1
+        )
+        [ -z "@option.opsman-ssh-password@" ] && (
+        	echo "ERROR! The Rundeck job runtime variable \"opsman-ssh-password\" has not been set."
         	exit 1
         )
 
@@ -128,6 +136,7 @@
         	if [[ $? -ne 0 ]]; then
         		rm -fr $BACKUP_TIMESTAMP_DIR
         		echo "ERROR! Backup of tile '$t' failed."
+        		exit 1
         	fi
         done
 
